### PR TITLE
moved parsers classes into parsers package

### PR DESCRIPTION
**Pull request by EFregnan**
Hi, as discussed yesterday I moved all parsers classes into a "\parsers" package to keep them separate from the other classes.

I took the chance the update the copyright on all classes touched by this change. 

Please, let me know if I overlooked something or if there is something that must be changed. 

Thanks a lot.

### CODE REVIEW

**Comment by EFregnan** [comment]
Uhm... it looks like moving the parser classes broke three tests in GerritRestClientTest: e.g., testGerritAuthExtractionAndCache.

I will look into it as soon as I can. 

@uwolfer, do you have any idea on what might have happened?

**Comment by uwolfer** [comment]
> @uwolfer, do you have any idea on what might have happened?

I've seen that, but I do not have an idea right now.

**Comment by EFregnan** [comment]
Moving changes.json up from the changes/parsers folder to the changes folder fixed this bug.

I still have no idea why it happened though. 

@uwolfer, if you agree we could merge this and open an issue so I can investigate the cause in the next weeks.

**Comment by uwolfer** [comment]
> Moving changes.json up from the changes/parsers folder to the changes folder fixed this bug.

Ah, now I got it! The integration tests spin up a Jetty webserver, which serves the JSON files exactly in the structure as they are in the filesystem. With moving `changes.json` to  `changes/parsers`, it was not delivered anymore in `changes/` and thus the tests failed because a 404 (not found) was returned by the webserver. That makes sense, and I don't think you need to spend more time in analyzing it.

**Comment by EFregnan** [comment]
>Ah, now I got it! The integration tests spin up a Jetty webserver, which serves the JSON files exactly in the structure as they are in the filesystem. With moving changes.json to changes/parsers, it was not delivered anymore in changes/ and thus the tests failed because a 404 (not found) was returned by the webserver. That makes sense, and I don't think you need to spend more time in analyzing it.

I see. Thank you for finding out what the problem was. 

Yes, there is no need to open an issue at this point. 

Changes.json is the only file affected by this. To be sure I understood correctly, you suggest to simply duplicate changes.json and leave a copy in _changes_ while moving the other to _changes/parsers_, right? 
If that's what you meant, it's fine for me.

**Comment by uwolfer** [comment]
> Changes.json is the only file affected by this. To be sure I understood correctly, you suggest to simply duplicate changes.json and leave a copy in _changes_ while moving the other to _changes/parsers_, right?
> If that's what you meant, it's fine for me.

Yes, this was my idea.

**Comment by EFregnan** [comment]
Great! This commit should have addressed your suggestion.

**Pull request merged**
