### PR TITLE
Fix tests on Windows

### PR DESCRIPTION
**Pull request by sschuberth**
With these commits, all tests pass on Windows.

@uwolfer Have you considered using AppVeyor in addition to Travis CI in order to run tests on Windows and prevent future regressions?

### CODE REVIEW

**Comment by uwolfer** [comment]
Btw, is there any reason not to set the same line endings for any file type? At the moment line endings in this project depend on the OS they were created on?

**Comment by sschuberth** [comment]
I'm usually not a fan of enforcing platform-specific behavior unless absolutely required. In my experience it sometimes shadows bad programming practices where one makes too strict assumptions instead of writing generic code.

**Comment by uwolfer** [comment]
@sschuberth: Thanks for the  AppVoyeur hint - I have just looked into it. I think it would be easy to setup (but not as easy as Travis), but I'm not sure if it's worth to maintain a second testing infrastructure. E.g. Maven needs to be setup manually if I understand it correctly (have looked into some other GitHub projects using it).

**Comment by sschuberth** [comment]
See PR #38, setting up Maven for AppVeyor is not much of an issue. Also, I don't think (or hope) there's much to maintain. But of course it's only a suggestion from my side, just take a look whether you like it.

**Comment by uwolfer** [comment]
@sschuberth: Great work - thank you very much! :+1:

**Pull request merged**
