### PR TITLE
Implement get commit api

### PR DESCRIPTION
**Pull request by build-developonbox-ru**

### CODE REVIEW

**Comment by uwolfer** [comment]
@thesvistun: Thanks. Would be nice if you could get it building by CI. I think there is not much to fix.

**Comment by thesvistun** [comment]
@uwolfer, Looks like Travis environment to test with java8 is broken.
https://travis-ci.org/uwolfer/gerrit-rest-java-client/jobs/610810882?utm_medium=notification&utm_source=github_status

**Comment by uwolfer** [comment]
@thesvistun: I've just fixed Travis build on master. Please rebase this PR.

**Comment by uwolfer** [comment]
@thesvistun: Thank you!

**Pull request merged**
