### PR TITLE
Add support for "Changes Submitted Together"

### PR DESCRIPTION
**Pull request by johannesc**
This adds support to get a list of ChangeInfo that will be
submitted together.

### CODE REVIEW

**Comment by uwolfer** [comment]
Thanks! Would be nice if you could add a test case.

**Comment by johannesc** [comment]
> Thanks! Would be nice if you could add a test case.

I will try! It was not obvious too me how to do it though, so if you have any pointers it would be great :)

**Comment by uwolfer** [comment]
I think there are similar examples in this class: https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/test/java/com/urswolfer/gerrit/client/rest/http/changes/ChangeApiRestClientTest.java#L306

**Comment by johannesc** [comment]
I have added a test case now. Please let me know if there is anything else you like me to change!

**Comment by johannesc** [comment]
Thanks! I have one more PR coming up, so need for a release before that.

**Pull request merged**
