### PR TITLE
Use HttpClient packages for Android maintained by Marek Sebera

### PR DESCRIPTION
**Pull request by sschuberth**
See https://github.com/smarek/httpclient-android/wiki/Project-Introduction
for details.

### CODE REVIEW

**Comment by sschuberth** [comment]
@EdwinKempin Mind having a look, too? This would allow is to drop ` useLibrary 'org.apache.http.legacy'` from [reviewit](https://gerrit-review.googlesource.com/#/admin/projects/apps/reviewit).

**Comment by uwolfer** [comment]
@sschuberth: I cannot test this easily. Do you think there are any drawbacks when using this new lib instead of the "old" one? E.g. compatibility with older versions of Android?

**Comment by sschuberth** [comment]
> I cannot test this easily.

Well, you could build [reviewit](https://gerrit-review.googlesource.com/#/admin/projects/apps/reviewit) against it, which is not *that* hard, esp. with [JitPack](https://jitpack.io/). But I can also do this next week.

> E.g. compatibility with older versions of Android?

I'm trusting the author here, who [says](https://github.com/smarek/httpclient-android/issues/12#issuecomment-246116830): "Truth is, that library itself is built with SDK v23, but again, it is both backward and forward compatible. And it does not affect in any way the API target you have in your application".

**Comment by uwolfer** [comment]
@p4r4n01d: Can you please look into this PR?

**Comment by uwolfer** [comment]
I think with this PR, all differences between branch `master` and `httpclient-android` are gone which is great (except the different dependencies in `pom.xml`).

Probably we could even get rid of the branch `httpclient-android` (because it requires additional efforts to maintain and release)? I think it should be possible to use the release based on `master` also for Android projects and just exclude the "normal" httpclient dependency in pom.xml of the user of this lib and instead add the dependency to `cz.msebera.android:httpclient`?

Of course, this must be documented in README if it works. What do you think?

**Comment by p4r4n01d** [comment]
I don't think it will be that simple. The link posted mentions the following compatibility issue:

"In your code you'll have to use classes from package cz.msebera.android.httpclient instead of org.apache.http".

Looking at the changes, the imports are using the wrong packages ask would likely conflict with those in Android.

I am not actively maintaining any projects which use this library so I won't get to test whether this works for a while.

**Comment by sschuberth** [comment]
> Looking at the changes, the imports are using the wrong packages ask would likely conflict with those in Android.

Bummer, you're absolutely right. It would have been too easy ... I'll close the PR.

@uwolfer Are you still interested in d71f8c109708c621c00236304ab7c47be3ad4154? If so, will you just cherry-pick, or do you want me to file another PR?

**Comment by uwolfer** [comment]
@sschuberth: I think https://github.com/uwolfer/gerrit-rest-java-client/commit/d71f8c109708c621c00236304ab7c47be3ad4154 is already merged with PR #64?

**Comment by sschuberth** [comment]
But only for the `master` branch. The Android branch did not receive the work-around, so nothing needs to be reverted, but still the Maven package version needs to be bumped.

**Comment by sschuberth** [comment]
@uwolfer Here's a new PR with only the Maven version bump in the httpclient-android branch for your convenience: https://github.com/uwolfer/gerrit-rest-java-client/pull/65

**Pull request closed without merging**
