### PR TITLE
Impl. create method of changes

### PR DESCRIPTION
**Pull request by hongkailiu**

### CODE REVIEW

**Comment by uwolfer** [comment]
Thank you!

**Comment by hongkailiu** [comment]
When can we expect to see a new release including this change? ^_^

**Comment by uwolfer** [comment]
@hongkailiu: I won't be able to do this in the next days. You could use https://jitpack.io until I create a new release.

**Comment by hongkailiu** [comment]
Understood. Thanks for the reply.

**Comment by uwolfer** [comment]
@hongkailiu: I have just pushed a new release: v0.8.12.

**Pull request merged**
